"""Bake the orbital-station reference model's material set into two 2x2 atlases.

The model itself is a kit whose parts all sit at the origin — the exported node
transforms are gone — so the geometry is worth nothing.  The materials are worth
a great deal: four hand-painted hull sets, each with a base colour and an
emissive pass, which is exactly what a station built out of untextured quads is
missing.  We keep the textures and throw the mesh away.
"""
import json, struct, io, base64, numpy as np
from PIL import Image, ImageEnhance

D = '/root/.claude/uploads/edb7f323-3b09-5a52-ab50-ad834433858e/'
b = open(D + 'ebba7a06-simple_orbital_space_station.glb', 'rb').read()
jl = struct.unpack_from('<I', b, 12)[0]
J = json.loads(b[20:20 + jl].decode('utf8'))
BIN = b[20 + jl + ((4 - jl % 4) % 4) + 8:]

def img(i):
    v = J['bufferViews'][J['images'][i]['bufferView']]
    o = v.get('byteOffset', 0)
    return Image.open(io.BytesIO(BIN[o:o + v['byteLength']])).convert('RGB')

T = 512

def fit(im, tilev=1):
    """Resample to a TxT tile.  tilev=2 stacks the source twice instead of
    stretching it, for the deck pattern whose hexes must stay round."""
    if tilev == 1:
        return im.resize((T, T), Image.LANCZOS)
    h = T // tilev
    out = Image.new('RGB', (T, T))
    s = im.resize((T, h), Image.LANCZOS)
    for k in range(tilev):
        out.paste(s, (0, k * h))
    return out

def normalise(im, target=0.55, gain=1.0):
    """Level the tile to a common mean so the vertex tint, not the texture,
    decides how light a surface is."""
    a = np.asarray(im).astype(np.float32) / 255.0
    m = a.mean()
    if m > 1e-3:
        a *= target / m
    a *= gain
    return Image.fromarray((np.clip(a, 0, 1) * 255).astype(np.uint8))

def boost(im, gain):
    a = np.asarray(im).astype(np.float32) / 255.0 * gain
    return Image.fromarray((np.clip(a, 0, 1) * 255).astype(np.uint8))

# tile 0 hull plating, 1 dark plating, 2 gold tech panel, 3 hex deck
base = [normalise(fit(img(0)), 0.58),
        normalise(fit(img(4)), 0.46),
        normalise(fit(img(7)), 0.50),
        normalise(fit(img(11), 2), 0.30)]
emis = [boost(fit(img(2)), 1.7),
        boost(fit(img(2).transpose(Image.ROTATE_90)), 1.7),
        boost(fit(img(9)), 1.25),
        boost(fit(img(13), 2), 1.0)]

def atlas(tiles):
    a = Image.new('RGB', (T * 2, T * 2))
    for i, t in enumerate(tiles):
        a.paste(t, ((i % 2) * T, (i // 2) * T))
    return a

ab, ae = atlas(base), atlas(emis)
ab.save('st-atlas-base.png'); ae.save('st-atlas-emi.png')

def jpg(im, q):
    buf = io.BytesIO(); im.save(buf, 'JPEG', quality=q, optimize=True)
    return buf.getvalue()

db, de = jpg(ab, 86), jpg(ae, 80)
print('base %d KB  emissive %d KB' % (len(db) // 1024, len(de) // 1024))

out = ("'use strict';\n"
       "/* Generated by tools/bakestation.py — do not edit.\n"
       "   Two 2x2 atlases lifted from a station model whose geometry was\n"
       "   unusable: base colour and emissive, tiles in the order\n"
       "   0 hull plating, 1 dark plating, 2 tech panel, 3 hex deck.\n"
       "   PIL writes the first tile top-left, and the runtime uploads flipped,\n"
       "   so tile 0 lands in the TOP half of the GL texture. */\n"
       "const STATION_TEX = {\n  tiles: 2,\n"
       "  base: 'data:image/jpeg;base64," + base64.b64encode(db).decode() + "',\n"
       "  emissive: 'data:image/jpeg;base64," + base64.b64encode(de).decode() + "'\n};\n")
open('/home/user/test/js/stationtex.js', 'w').write(out)
print('wrote js/stationtex.js  %.2f MB' % (len(out) / 1e6))
